module Graphics.Vulkan.Ext.ColorSpace where

import qualified Graphics.Vulkan.Ext.VK_EXT_swapchain_colorspace as Vk
import qualified Graphics.Vulkan.Ext.VK_KHR_surface as Vk

data VkColorSpaceKHR
  = SRGB_NONLINEAR_KHR
  | DISPLAY_P3_NONLINEAR_EXT
  | EXTENDED_SRGB_LINEAR_EXT
  | DCI_P3_LINEAR_EXT
  | DCI_P3_NONLINEAR_EXT
  | BT709_LINEAR_EXT
  | BT709_NONLINEAR_EXT
  | BT2020_LINEAR_EXT
  | HDR10_ST2084_EXT
  | DOLBYVISION_EXT
  | HDR10_HLG_EXT
  | ADOBERGB_LINEAR_EXT
  | ADOBERGB_NONLINEAR_EXT
  | PASS_THROUGH_EXT
  | EXTENDED_SRGB_NONLINEAR_EXT
  -- | DISPLAY_NATIVE_AMD
  deriving (Eq, Ord, Show)

vkColorSpaceKHR :: Vk.VkColorSpaceKHR -> VkColorSpaceKHR
vkColorSpaceKHR a =
  case a of
    Vk.VK_COLOR_SPACE_SRGB_NONLINEAR_KHR -> SRGB_NONLINEAR_KHR
    Vk.VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT -> DISPLAY_P3_NONLINEAR_EXT
    Vk.VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT -> EXTENDED_SRGB_LINEAR_EXT
    Vk.VK_COLOR_SPACE_DCI_P3_LINEAR_EXT -> DCI_P3_LINEAR_EXT
    Vk.VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT -> DCI_P3_NONLINEAR_EXT
    Vk.VK_COLOR_SPACE_BT709_LINEAR_EXT -> BT709_LINEAR_EXT
    Vk.VK_COLOR_SPACE_BT709_NONLINEAR_EXT -> BT709_NONLINEAR_EXT
    Vk.VK_COLOR_SPACE_BT2020_LINEAR_EXT -> BT2020_LINEAR_EXT
    Vk.VK_COLOR_SPACE_HDR10_ST2084_EXT -> HDR10_ST2084_EXT
    Vk.VK_COLOR_SPACE_DOLBYVISION_EXT -> DOLBYVISION_EXT
    Vk.VK_COLOR_SPACE_HDR10_HLG_EXT -> HDR10_HLG_EXT
    Vk.VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT -> ADOBERGB_LINEAR_EXT
    Vk.VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT -> ADOBERGB_NONLINEAR_EXT
    Vk.VK_COLOR_SPACE_PASS_THROUGH_EXT -> PASS_THROUGH_EXT
    Vk.VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT -> EXTENDED_SRGB_NONLINEAR_EXT
    -- Vk.VK_COLOR_SPACE_DISPLAY_NATIVE_AMD -> DISPLAY_NATIVE_AMD
    Vk.VK_COLORSPACE_SRGB_NONLINEAR_KHR -> SRGB_NONLINEAR_KHR

unVkColorSpaceKHR :: VkColorSpaceKHR -> Vk.VkColorSpaceKHR
unVkColorSpaceKHR a =
  case a of
    SRGB_NONLINEAR_KHR -> Vk.VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
    DISPLAY_P3_NONLINEAR_EXT -> Vk.VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
    EXTENDED_SRGB_LINEAR_EXT -> Vk.VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
    DCI_P3_LINEAR_EXT -> Vk.VK_COLOR_SPACE_DCI_P3_LINEAR_EXT
    DCI_P3_NONLINEAR_EXT -> Vk.VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT
    BT709_LINEAR_EXT -> Vk.VK_COLOR_SPACE_BT709_LINEAR_EXT
    BT709_NONLINEAR_EXT -> Vk.VK_COLOR_SPACE_BT709_NONLINEAR_EXT
    BT2020_LINEAR_EXT -> Vk.VK_COLOR_SPACE_BT2020_LINEAR_EXT
    HDR10_ST2084_EXT -> Vk.VK_COLOR_SPACE_HDR10_ST2084_EXT
    DOLBYVISION_EXT -> Vk.VK_COLOR_SPACE_DOLBYVISION_EXT
    HDR10_HLG_EXT -> Vk.VK_COLOR_SPACE_HDR10_HLG_EXT
    ADOBERGB_LINEAR_EXT -> Vk.VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT
    ADOBERGB_NONLINEAR_EXT -> Vk.VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
    PASS_THROUGH_EXT -> Vk.VK_COLOR_SPACE_PASS_THROUGH_EXT
    EXTENDED_SRGB_NONLINEAR_EXT -> Vk.VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
    -- DISPLAY_NATIVE_AMD -> Vk.VK_COLOR_SPACE_DISPLAY_NATIVE_AMD
